# Generated by Django 5.1.7 on 2025-04-16 16:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VRPPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên điểm')),
                ('point_type', models.CharField(choices=[('DEPOT', 'Kho hàng'), ('AGENT', 'Đại lý')], default='AGENT', max_length=5, verbose_name='Loại điểm')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('load', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tải trọng (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Điểm trên bản đồ',
                'verbose_name_plural': 'Các điểm trên bản đồ',
            },
        ),
        migrations.CreateModel(
            name='VRPProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bài toán')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('vehicle_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Công suất xe (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('depot', models.ForeignKey(limit_choices_to={'point_type': 'DEPOT'}, on_delete=django.db.models.deletion.PROTECT, related_name='depot_problems', to='VRP1.vrppoint', verbose_name='Kho hàng')),
            ],
            options={
                'verbose_name': 'Bài toán VRPTW',
                'verbose_name_plural': 'Các bài toán VRPTW',
            },
        ),
        migrations.CreateModel(
            name='RoutingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.PositiveIntegerField(verbose_name='Số xe')),
                ('total_distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng khoảng cách (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_plans', to='VRP1.vrpproblem', verbose_name='Bài toán')),
            ],
            options={
                'verbose_name': 'Kế hoạch tuyến đường',
                'verbose_name_plural': 'Các kế hoạch tuyến đường',
            },
        ),
        migrations.CreateModel(
            name='RouteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.PositiveIntegerField(verbose_name='Số thứ tự xe')),
                ('visit_order', models.PositiveIntegerField(verbose_name='Thứ tự thăm')),
                ('arrival_time', models.DateTimeField(verbose_name='Thời gian đến')),
                ('distance_from_previous', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Khoảng cách từ điểm trước (km)')),
                ('routing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_details', to='VRP1.routingplan', verbose_name='Kế hoạch tuyến đường')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VRP1.vrppoint', verbose_name='Điểm đến')),
            ],
            options={
                'verbose_name': 'Chi tiết tuyến đường',
                'verbose_name_plural': 'Chi tiết các tuyến đường',
                'ordering': ['vehicle_id', 'visit_order'],
                'unique_together': {('routing_plan', 'vehicle_id', 'visit_order')},
            },
        ),
    ]
