# Generated by Django 5.1.7 on 2025-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRP1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routingplan',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='vrpproblem',
            name='depot',
        ),
        migrations.AlterModelOptions(
            name='vrpproblem',
            options={},
        ),
        migrations.RemoveField(
            model_name='vrpproblem',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='vrpproblem',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='vrpproblem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vrpproblem',
            name='vehicle_capacity',
        ),
        migrations.AddField(
            model_name='vrpproblem',
            name='agents_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='vrpproblem',
            name='depot_coords',
            field=models.CharField(default='21.0278,105.8342', max_length=100),
        ),
        migrations.AddField(
            model_name='vrpproblem',
            name='solution_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vrpproblem',
            name='vehicle_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vrpproblem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vrpproblem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='RouteDetail',
        ),
        migrations.DeleteModel(
            name='RoutingPlan',
        ),
        migrations.DeleteModel(
            name='VRPPoint',
        ),
    ]
